### ISSUE TITLE
Constant FILTER_SANITIZE_STRING is deprecated in .../Classes/Utility/SvgUtility.php line 71

### ISSUE THREAD

**Issue by mediaessenz** [benjaminkott/bootstrap_package#1168]
# Bug Report

## Description

I get this exception in the frontend when using bootstrap_package 12.0.5 under TYPO3 11 with php 8.1:
```
PHP Runtime Deprecation Notice: Constant FILTER_SANITIZE_STRING is deprecated in /.../typo3conf/ext/bootstrap_package/Classes/Utility/SvgUtility.php line 71
```
Since php version 8.1  FILTER_SANITIZE_STRING is deprecated:
"Strip tags and HTML-encode double and single quotes, optionally strip or encode special characters. Encoding quotes can be disabled by setting FILTER_FLAG_NO_ENCODE_QUOTES. (Deprecated as of PHP 8.1.0, use [htmlspecialchars()](https://www.php.net/manual/en/function.htmlspecialchars.php) instead.)"

Source: https://www.php.net/manual/en/filter.filters.sanitize.php

## Steps to Reproduce

1. Install TYPO3 11 + BP 12 under PHP 8.1 
2. Create a page from a template which uses the InlineSvgViewHelper of bootstrap_package
3. Open this page in the frontend

### Expected behavior

Show the page without an exception

### Actual behavior

The exception descripted up appears.

## Versions

TYPO3 11.5.10
PHP 8.1.1
bootstrap_package 12.0.5

**Comment by dkd-kaehm** [comment]
Isn't it fixed in 061a6d8 and a1e6d1d
Can be closed?

**Comment by urbreal** [comment]
This bug is still not fixed!
Error exception descripted up appears f.e if you use the "icon group" content element and select an icon (svg) from the  icon-set libs "ionicons" or "glyphicons".

**Comment by TB-effective** [comment]
> Isn't it fixed in [061a6d8](https://github.com/benjaminkott/bootstrap_package/commit/061a6d84486c8f0040f85c527bc341bb524f5db6) and [a1e6d1d](https://github.com/benjaminkott/bootstrap_package/commit/a1e6d1d4e9f848ed8b72cc3e97be4dad4819630b) Can be closed?

It seems that commit has not been merged to any release yet. Latest is 12.0.5 from April, which still exhibits this problem.

**Comment by benjaminkott** [comment]
can be considered as resolved with v13
